# Generated by Django 4.2.1 on 2023-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('clg_name', models.CharField(max_length=200)),
                ('exam', models.CharField(max_length=100)),
                ('board10', models.CharField(max_length=200)),
                ('marks10', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
