# Generated by Django 4.2.1 on 2023-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0003_exam_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Exam_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
