# Generated by Django 4.2.1 on 2023-06-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0004_exam_exam_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_history',
            old_name='ans_list',
            new_name='user_ans',
        ),
    ]
