# Generated by Django 4.2.1 on 2023-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0005_rename_ans_list_exam_history_user_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Exam_status',
            new_name='exam_status',
        ),
        migrations.AlterField(
            model_name='exam_history',
            name='exam_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_history',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
