# Generated by Django 4.2.1 on 2023-06-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0006_rename_exam_status_exam_exam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_history',
            name='user_ans',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
