# Generated by Django 4.2.1 on 2023-06-12 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0008_alter_exam_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exam_data',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_data',
            name='marks',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='exam_data',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exam_history',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_history',
            name='question_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_history',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam_data',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='cetapp.exam'),
        ),
        migrations.AlterField(
            model_name='exam_data',
            name='img',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exam_history',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_id', to='cetapp.exam'),
        ),
        migrations.AlterField(
            model_name='exam_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cetapp.userdata'),
        ),
    ]
