# Generated by Django 4.2.1 on 2023-07-07 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0009_exam_created_at_exam_updated_at_exam_data_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='board10',
            new_name='board_10',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='clg_name',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='marks10',
            new_name='marks_10',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_status',
        ),
        migrations.RemoveField(
            model_name='exam_data',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exam_data',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exam_data',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam_data',
            name='subject',
            field=models.CharField(default='maths', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam_data',
            name='img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='exam_data',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Exam_history',
        ),
    ]
