# Generated by Django 4.2.1 on 2023-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0010_rename_board10_userdata_board_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_marks',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
