# Generated by Django 4.2.1 on 2023-07-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0013_exam_history_h_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_history',
            old_name='h_question',
            new_name='h_questions',
        ),
    ]
