# Generated by Django 4.2.1 on 2023-07-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0014_rename_h_question_exam_history_h_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_ans', models.CharField(max_length=100)),
                ('h_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_exam', to='cetapp.exam')),
                ('h_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_question', to='cetapp.exam_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cetapp.userdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Exam_history',
        ),
    ]
