# Generated by Django 4.2.1 on 2023-07-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetapp', '0015_user_history_delete_exam_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_history',
        ),
    ]
